// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgtfsdtkcanclvvmbuse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndGZzZHRrY2FuY2x2dm1idXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzAxMTgsImV4cCI6MjA2ODUwNjExOH0.wfsplVRz144mzaeOfGKj29dzrZjq6Xluur-OcmMSUhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});